---
apiVersion: v1
kind: Service
metadata:
  name: sshd-jumpserver
  labels:
    name: sshd-jumpserver
spec:
  type: "LoadBalancer"
  ports:
  - name: ssh
    port: 2222
    targetPort: 22
  selector:
    app: sshd-jumpserver
